title: My Knowledge Base
theme: just-the-docs

search_enabled: true

nav:
  - title: External Docs
    children:
      - title: Shopify User Guide
        url: /external-docs/shopify-user-guide
      - title: Zendesk Knowledge Articles
        url: /external-docs/zendesk-knowledge-articles
      - title: API Documentation
        url: /external-docs/api-documentation

  - title: Internal Docs
    children:
      - title: Internal SOP
        url: /internal-docs/internal-sop

  - title: Case Studies
    children:
      - title: Chaos to Clarity
        url: /case-studies/chaos-to-clarity-case

  - title: AI + Technical Writing
    children:
      - title: Prompt Engineering Guide
        url: /ai-technical-writing/ai-prompt-engineering-guide
